"""add branches

Revision ID: 7a61a0ae5b60
Revises: 28bf610acfa1
Create Date: 2025-12-24 14:47:17.265245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a61a0ae5b60'
down_revision = '28bf610acfa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
