"""Add is_active to Employee

Revision ID: 0d6f3efdcebc
Revises: 3135617a5294
Create Date: 2025-11-29 19:22:56.954288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6f3efdcebc'
down_revision = '3135617a5294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('admins_business_id_key'), type_='unique')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('admins_business_id_key'), ['business_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
