"""add goals and expenses tables

Revision ID: 56493a8df0dc
Revises: a1b2c3d4e5f6
Create Date: 2026-03-17 22:54:29.112918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56493a8df0dc'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('goal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'branch_id', 'year', 'month', name='uq_goal')
    )
    with op.batch_alter_table('branch_item_overrides', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('branch_item_overrides_branch_id_item_id_key'), type_='unique')
        batch_op.create_unique_constraint('_branch_item_uc', ['branch_id', 'item_id'])

    with op.batch_alter_table('business_holidays', schema=None) as batch_op:
        batch_op.alter_column('is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.drop_constraint(batch_op.f('business_holidays_business_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])

    with op.batch_alter_table('business_hours', schema=None) as batch_op:
        batch_op.alter_column('is_open',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('biz_branch_day_uc'))
        batch_op.drop_constraint(batch_op.f('business_hours_business_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('payment_cash',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('payment_card',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('payment_points',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('allow_deferred',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('points_per_peso',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
        batch_op.alter_column('peso_per_point',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
        batch_op.alter_column('discount_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('max_discount_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('50.0'))
        batch_op.alter_column('normal_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
        batch_op.alter_column('urgent_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('extra_urgent_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('urgent_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('20.0'))
        batch_op.alter_column('extra_urgent_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('50.0'))

    with op.batch_alter_table('client_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('client_types_name_business_id_key'), type_='unique')
        batch_op.create_unique_constraint('_client_type_business_uc', ['name', 'business_id'])

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('points_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))

    with op.batch_alter_table('order_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_payments_order_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('amount_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('urgency',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('urgency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'normal'::character varying"))
        batch_op.alter_column('amount_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))

    with op.batch_alter_table('order_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_payments_order_id_fkey'), 'orders', ['order_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('points_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))

    with op.batch_alter_table('client_types', schema=None) as batch_op:
        batch_op.drop_constraint('_client_type_business_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('client_types_name_business_id_key'), ['name', 'business_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('extra_urgent_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('50.0'))
        batch_op.alter_column('urgent_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('20.0'))
        batch_op.alter_column('extra_urgent_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('urgent_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('normal_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
        batch_op.alter_column('max_discount_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('50.0'))
        batch_op.alter_column('discount_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('peso_per_point',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
        batch_op.alter_column('points_per_peso',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
        batch_op.alter_column('allow_deferred',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('payment_points',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('payment_card',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('payment_cash',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('business_hours', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('business_hours_business_id_fkey'), 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('biz_branch_day_uc'), ['business_id', sa.literal_column("COALESCE(branch_id, '-1'::integer)"), 'day_of_week'], unique=True)
        batch_op.alter_column('is_open',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('business_holidays', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('business_holidays_business_id_fkey'), 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('branch_item_overrides', schema=None) as batch_op:
        batch_op.drop_constraint('_branch_item_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('branch_item_overrides_branch_id_item_id_key'), ['branch_id', 'item_id'], postgresql_nulls_not_distinct=False)

    op.drop_table('monthly_goals')
    op.drop_table('expenses')
    # ### end Alembic commands ###
