"""Add client birthday and adjust address fields

Revision ID: 68b390f83c72
Revises: 231e6c677300
Create Date: 2025-11-09 06:04:40.915523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b390f83c72'
down_revision = '231e6c677300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('street_and_number', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth_month', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('date_of_birth_month')
        batch_op.drop_column('date_of_birth_day')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('street_and_number')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
