"""empty message

Revision ID: ff0bf9f178fd
Revises: 3eb497e8a6b7
Create Date: 2025-10-04 08:34:03.062325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0bf9f178fd'
down_revision = '3eb497e8a6b7'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Crear la nueva tabla 'branches' (Sucursales)
    op.create_table('branches',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('address', sa.String(length=255), nullable=True),
        sa.Column('business_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 2. Modificar la tabla 'admins'
    with op.batch_alter_table('admins', schema=None) as batch_op:
        # AÑADIR: la nueva columna branch_id (opcional)
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        # AÑADIR: la clave foránea para branch_id
        batch_op.create_foreign_key(batch_op.f('fk_admins_branch_id_branches'), 'branches', ['branch_id'], ['id'])
        # ELIMINAR: la restricción unique del business_id (para que los empleados puedan compartir business_id)
        batch_op.drop_constraint('admins_business_id_key', type_='unique')


    # 3. Modificar la tabla 'items'
    with op.batch_alter_table('items', schema=None) as batch_op:
        # AÑADIR: la nueva columna branch_id (OPCIONAL/NULLABLE)
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        
        # AÑADIR: la clave foránea para branch_id
        batch_op.create_foreign_key(batch_op.f('fk_items_branch_id_branches'), 'branches', ['branch_id'], ['id'])
        
        # ELIMINAR: la antigua clave foránea de business_id
        # Nota: El nombre de la clave foránea puede variar. Usa 'items_business_id_fkey' como un intento común.
        try:
            batch_op.drop_constraint('items_business_id_fkey', type_='foreignkey')
        except Exception:
            # Ignora si el nombre de la clave es diferente o no existe
            pass
            
        # ELIMINAR: la columna business_id (la que causaba el error de NOT NULL)
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('business_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
